[application]
name = "stackery"
default_platform = "web"
out_dir = "dist"
assets_dir = "public"

[web.app]
title = "stackery"

[web.watcher]
watch_path = ["src", "public"]

[web.resource]
style = ["/style.css", "/style/editor.css", "/style/md.css"]
script = []

[web.resource.dev]
script = []
