[package]
name = "stac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
parity-wasm = "0.45.0"
scoped-arena = { version = "0.4.1", features = ["alloc", "allocator_api"] }
