[package]
name = "serde-base128"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-base128-derive = { path = "../serde-base128-derive" }
